In [1]:
import numpy as np

### 1. *Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

In [2]:
def calc_logloss(y, y_pred):
    ### ИЗМЕНЕНИЯ
    y_pred = abs(y_pred - 1e-16)
    ### КОНЕЦ ИЗМЕНЕНИЙ
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [3]:
# Пример применения
y1 = np.array([1, 0])
y_pred1 = np.array([0.8, 0.1])
calc_logloss(y1, y_pred1)

0.164252033486018

In [4]:
# Плохой пример применения
y1 = np.array([1, 0])
y_pred1 = np.array([1, 0.1])
calc_logloss(y1, y_pred1)

0.052680257828913134

### 2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [5]:
X = np.array([ [   1,    1,  500,    1],
               [   1,    1,  700,    1],
               [   1,    2,  750,    2],
               [   1,    5,  600,    1],
               [   1,    3, 1450,    2],
               [   1,    0,  800,    1],
               [   1,    5, 1500,    3],
               [   1,   10, 2000,    3],
               [   1,    1,  450,    1],
               [   1,    2, 1000,    2]], dtype = np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)

In [6]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))


# стандартизация
def std_scale(X, ddof=0):
    mean = X.mean()
    std = (sum((X - mean)**2)/(X.shape[0]-ddof))**(1/2)
    return (X - mean)/std

In [7]:
# стандартизация признаков
X_std = X.copy().astype(np.float64)
X_std[:, 1] = std_scale(X_std[:, 1])
X_std[:, 2] = std_scale(X_std[:, 2])

In [8]:
def eval_model(X, y, iterations, eta=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[1])
    n = X.shape[0]
    
    for i in range(iterations):
        z = np.dot(X, W)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X.T @ (y_pred - y)
        W -= eta * dQ
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [9]:
W = eval_model(X_std, y, int(1e5), eta=1e-2)

0 [ 0.49264598 -0.13935538  0.64759106  1.51705001] 1.3696877789393176
10000 [-3.71598667 -1.76918281  0.21414146  2.22440225] 0.41523623845467983
20000 [-5.80148748 -2.05585378 -0.36139765  3.45327472] 0.35167963404575103
30000 [-7.28184208 -2.28046412 -0.75867997  4.3494258 ] 0.3194405198711246
40000 [-8.4423199  -2.47365656 -1.05731851  5.06455632] 0.29952545963991384
50000 [-9.41218385 -2.64340472 -1.30100906  5.66969833] 0.285547808143208
60000 [-10.25805197  -2.79579611  -1.51061629   6.2021284 ] 0.2748738598125055
70000 [-11.01770473  -2.93525218  -1.69712703   6.6832868 ] 0.266239118239767
80000 [-11.71420346  -3.06484942  -1.86693301   7.12642307] 0.2589643029059558
90000 [-12.36245884  -3.18672489  -2.0240544    7.54019871] 0.2526521651648525


In [10]:
eval_model(X_std, y, int(1e6), eta=1e-1)

0 [ 0.45603242 -0.14917513  0.64671373  1.46323139] 1.3696877789393176
100000 [-38.1838505   -8.32379309  -7.92054892  24.07736088] 0.12693123785588026
200000 [-50.96669956 -10.83407968 -10.78286909  32.19981402] 0.10205862840216058
300000 [-59.89447229 -12.49999437 -12.83301097  37.85609196] 0.09012483845885685
400000 [-67.17062681 -13.7798047  -14.55597042  42.4588893 ] 0.08223433152821821
500000 [-73.53786059 -14.8379091  -16.10592935  46.48316529] 0.07620229664417488
600000 [-79.32429222 -15.75572073 -17.5444838   50.13857134] 0.07122376184928339
700000 [-84.69540446 -16.57973922 -18.89888742  53.53073858] 0.06693523307385704
800000 [-89.74225092 -17.3375646  -20.18275853  56.71769833] 0.06314916910820423
900000 [-94.51922257 -18.04568331 -21.40424122  59.73404837] 0.05975726620055116


array([-99.06176016, -18.7141119 , -22.56914288,  62.60228745])

In [11]:
eval_model(X_std, y, int(1e6), eta=1)

0 [ 0.08989678 -0.24737262  0.63794047  0.92504521] 1.3696877789393176
100000 [-99.0631494  -18.71431584 -22.56949948  62.60316463] 0.0566894556581596
200000 [-135.37477214  -24.02479765  -31.90338405   85.53125301] 0.036844301939377745
300000 [-161.21439295  -27.81705943  -38.53603458  101.84815861] 0.0268495391079561
400000 [-181.07113469  -30.74097931  -43.62616496  114.38760117] 0.02096281798827271
500000 [-197.11320217  -33.10821956  -47.73490202  124.51836332] 0.017126206481658784
600000 [-210.53249633  -35.09131352  -51.1698649   132.99296381] 0.014443898450754767
700000 [-222.04659488  -36.79464848  -54.11589464  140.26448176] 0.01247026196586507
800000 [-232.11813577  -38.28576095  -56.69199729  146.62504011] 0.01096075298259729
900000 [-241.06160617  -39.61067925  -58.97898613  152.27322158] 0.009770769623888441


array([-249.09986201,  -40.80208545,  -61.03408263,  157.34975189])

In [12]:
eval_model(X_std, y, int(1e7), eta=1e2)

0 [-40.1850229  -11.04909639  -0.32711782 -58.27543437] 1.3696877789393176
1000000 [-607.01723064  -94.03612205 -152.41098723  383.40046274] 8.098327262986722e-05
2000000 [-657.51174407 -101.55275476 -165.29778544  415.29172382] 4.167622126797314e-05
3000000 [-687.58730814 -106.02986765 -172.97338859  434.28681327] 2.8056790046741146e-05
4000000 [-709.07936621 -109.22923668 -178.45837918  447.86074282] 2.1146114711120123e-05
5000000 [-725.81470169 -111.7205129  -182.7294015   458.43042727] 1.6966892254895212e-05
6000000 [-739.52192049 -113.76101724 -186.22761627  467.08761734] 1.4166955439261842e-05
7000000 [-751.13072391 -115.48914612 -189.19029376  474.41949264] 1.2160212259461446e-05
8000000 [-761.19910032 -116.98796266 -191.75983869  480.77846681] 1.0651429773025204e-05
9000000 [-770.08837432 -118.31125441 -194.02846493  486.39274481] 9.475719478747403e-06


array([-778.04597625, -119.49585444, -196.05931929,  491.41859841])

### 3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [13]:
def calc_pred_proba(W, X):
    y_pred_proba = sigmoid(X @ W)
    return y_pred_proba

In [14]:
calc_pred_proba(W, X_std)

array([0.35892525, 0.18610117, 0.99371639, 0.00334129, 0.68171061,
       0.31957259, 0.99783492, 0.12526593, 0.41189101, 0.98099967])

### 4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [15]:
def calc_pred(W, X):
    y_pred = np.round(sigmoid(X @ W))
    return y_pred

In [16]:
calc_pred(W, X_std)

array([0., 0., 1., 0., 1., 0., 1., 0., 0., 1.])

In [17]:
y

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

### 5. *Реализуйте функции для подсчета Accuracy, матрицы ошибок, точности и полноты, а также F1 score.

In [18]:
# В функциях к знаменателям прибавлены очень малые величины - во избежание деления на ноль

def calc_accuracy(y, y_pred):
    if not isinstance(y, (np.ndarray, list)) or not isinstance(y_pred, (np.ndarray, list)):
        raise TypeError('input must be a numpy.ndarray or list')
    else:
        y, y_pred = np.array(y), np.array(y_pred)
        if y.shape != y_pred.shape:
            raise ValueError(f'shape mismatch: "y" has shape {y.shape} and "y_pred" has shape {y_pred.shape}')
        else:
            return sum(y == y_pred)/(y.shape[0] + 1e-16)
    

def get_confusion_matrix(y, y_pred):
    if not isinstance(y, (np.ndarray, list)) or not isinstance(y_pred, (np.ndarray, list)):
        raise TypeError('input must be a numpy.ndarray or list')
    else:
        y, y_pred = np.array(y), np.array(y_pred)
        if y.shape != y_pred.shape:
            raise ValueError(f'shape mismatch: "y" has shape {y.shape} and "y_pred" has shape {y_pred.shape}')
        else:
            TP = sum((y == 1) & (y_pred == 1))
            FP = sum((y == 0) & (y_pred == 1))
            FN = sum((y == 1) & (y_pred == 0))
            TN = sum((y == 0) & (y_pred == 0))
            return np.array([[TP, FP], [FN, TN]])

    
def calc_precision(y, y_pred):
    if not isinstance(y, (np.ndarray, list)) or not isinstance(y_pred, (np.ndarray, list)):
        raise TypeError('input must be a numpy.ndarray or list')
    else:
        y, y_pred = np.array(y), np.array(y_pred)
        if y.shape != y_pred.shape:
            raise ValueError(f'shape mismatch: "y" has shape {y.shape} and "y_pred" has shape {y_pred.shape}')
        else:
            TP = sum((y == 1) & (y_pred == 1))
            FP = sum((y == 0) & (y_pred == 1))
            return TP/(TP + FP + 1e-16)

    
def calc_recall(y, y_pred):
    if not isinstance(y, (np.ndarray, list)) or not isinstance(y_pred, (np.ndarray, list)):
        raise TypeError('input must be a numpy.ndarray or list')
    else:
        y, y_pred = np.array(y), np.array(y_pred)
        if y.shape != y_pred.shape:
            raise ValueError(f'shape mismatch: "y" has shape {y.shape} and "y_pred" has shape {y_pred.shape}')
        else:
            TP = sum((y == 1) & (y_pred == 1))
            FN = sum((y == 1) & (y_pred == 0))
            return TP/(TP + FN + 1e-16)
    
    
def calc_f1(y, y_pred):
    precision = calc_precision(y, y_pred)
    recall = calc_recall(y, y_pred)
    return 2/(precision + recall + 1e-16) * precision * recall

Проверка

In [19]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [20]:
a = np.array([0., 1., 0., 1., 0., 0., 1.])
b = np.array([1, 1, 1, 0, 0, 1, 1])

# a = np.zeros(7)
# b = np.zeros(7)

# a = []
# b = []

In [21]:
accuracy_score(a, b), calc_accuracy(a, b)

(0.42857142857142855, 0.42857142857142855)

In [22]:
confusion_matrix(a, b), get_confusion_matrix(a, b)

(array([[1, 3],
        [1, 2]]),
 array([[2, 3],
        [1, 1]]))

In [23]:
precision_score(a, b), calc_precision(a, b)

(0.4, 0.4)

In [24]:
recall_score(a, b), calc_recall(a, b)

(0.6666666666666666, 0.6666666666666666)

In [25]:
f1_score(a, b), calc_f1(a, b)

(0.5, 0.5)

###  6. Могла ли модель переобучиться? Почему?

У модели были все шансы переобучиться. 

Из-за малого количества наблюдений у модели плохая обобщающая способность. 

Коэффициенты подбираются таким образом, чтобы увеличить расстояние от наблюдений до разделяющей гиперплоскости (ф-ция потерь logloss). Т.е. она будет построена так, что будет лучше всего разделять только эти наблюдения. 